# Generated by Django 5.1.6 on 2025-03-26 16:44

import django.db.models.deletion
import django.views.generic.detail
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryListView',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.post')),
            ],
            bases=('news.post', django.views.generic.detail.DetailView),
        ),
    ]
