# Generated by Django 5.1.6 on 2025-03-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_categorylistview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryListView',
        ),
    ]
